
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Feb 01 23:36:32 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LESSEQUALS = 37;
  public static final int PLUSPLUS = 27;
  public static final int IFEQUALS = 32;
  public static final int LBRACKET = 5;
  public static final int CHAR = 44;
  public static final int CONST = 11;
  public static final int IFNOTEQUALS = 33;
  public static final int LPAREN = 9;
  public static final int SEMI = 3;
  public static final int CONTINUE = 21;
  public static final int MINUS = 39;
  public static final int LESS = 36;
  public static final int FOR = 19;
  public static final int RPAREN = 10;
  public static final int AND = 41;
  public static final int OR = 40;
  public static final int BOOL = 45;
  public static final int MOREEQUALS = 35;
  public static final int COMMA = 4;
  public static final int CLASS = 14;
  public static final int DIV = 30;
  public static final int PLUS = 38;
  public static final int IF = 17;
  public static final int DOT = 26;
  public static final int ABSTRACT = 16;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 28;
  public static final int RETURN = 22;
  public static final int RBRACKET = 6;
  public static final int EQUAL = 12;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int NUMBER = 42;
  public static final int MOD = 31;
  public static final int IDENT = 43;
  public static final int BREAK = 20;
  public static final int VOID = 13;
  public static final int LBRACE = 7;
  public static final int ELSE = 18;
  public static final int READ = 23;
  public static final int RBRACE = 8;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int PRINT = 24;
  public static final int MORE = 34;
}

